project:
  type: website
  output-dir: docs

website:
  title: "Blog-Isaula"
  site-url: https://j-isaula.github.io/1619/
  navbar:
    right:
      - about.qmd
      - documentos.qmd
      - icon: github
        href: https://github.com/J-Isaula
      - icon: twitter
        href: https://twitter.com/isaula_juan
format:
  html:
    theme: flatly
    linkcolor: rgb(214, 122, 127)
    css: styles.css

editor: visual

