project:
  type: website
  resources:
    - keybase.txt
    - resume.pdf
    - cv.pdf

website:
  title: "Juan Isaula"
  site-url: https://mm218.dev
  description: "Technology and the Environment"
  open-graph:
    locale: en_US
  twitter-card:
    creator: "@JuanIsaula"
  comments:
    utterances:
      repo: mikemahoney218/mm218.dev
  navbar:
    right:
      - text: "Inicio"
        href: index.html
      - text: "Documentos"
        href: papers
      - text: "Blog"
        href: blog.html
      - icon: rss
        href: blog.xml
  cookie-consent: true
format:
  html:
    theme: [sandstone, _variables.scss]
    css: styles.css